//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrar.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventRegistrar.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungsmail.
        /// </summary>
        internal static string AcceptedMail {
            get {
                return ResourceManager.GetString("AcceptedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angebotene Sprachen.
        /// </summary>
        internal static string AngeboteneSprachen {
            get {
                return ResourceManager.GetString("AngeboteneSprachen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungseingang zuordnen.
        /// </summary>
        internal static string AssignIncoming {
            get {
                return ResourceManager.GetString("AssignIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsausgang zuordnen.
        /// </summary>
        internal static string AssignOutgoing {
            get {
                return ResourceManager.GetString("AssignOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzahlungen.
        /// </summary>
        internal static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail importiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ExternalMailImported {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ExternalMailImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Mailadresse korrigiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_InvalidAddresses_InvalidEmailAddressFixed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_InvalidAddresses_InvalidEmailAddressFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail freigegeben.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_MailReleased {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_MailReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlung zugeordnet.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Assignments_PaymentAssigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Assignments_PaymentAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungszuordnung zurückgenommen.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Assignments_PaymentUnassigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Assignments_PaymentUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug importiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_Fetch_BankStatementsFileImported {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_Fetch_BankStatementsFileImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug verarbeitet.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_PaymentFileProcessed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_PaymentFileProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild von Einzahlungsschein erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_Slips_PaymentSlipReceived {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_Slips_PaymentSlipReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezahlung am Checkin.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_PayAtCheckin_WillPayAtCheckinSet {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_PayAtCheckin_WillPayAtCheckinSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_PhoneMessages_SmsReceived {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_PhoneMessages_SmsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS gesendet.
        /// </summary>
        internal static string EventRegistrar_Backend_PhoneMessages_SmsSent {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_PhoneMessages_SmsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partypass reserviert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_FallbackToPartyPassSet {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_FallbackToPartyPassSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung von Warteliste nachgerückt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_PartnerSpotPromotedFromWaitingList {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_PartnerSpotPromotedFromWaitingLis" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Nachrücken aktiviert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_Promotion_AutomaticPromotionActivated {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_Promotion_AutomaticPromotionActiv" +
                        "ated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz von Warteliste nachgerückt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_SingleSpotPromotedFromWaitingList {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_SingleSpotPromotedFromWaitingList" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung storniert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung teilweise bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPartiallyPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPartiallyPai" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_SingleRegistrationPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_SingleRegistrationPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönlicher Rabatt gewährt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_IndividualReductions_IndividualReductionAdded {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_IndividualReductions_IndividualReductionAdde" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis wurde neu berechnet.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Price_PriceChanged {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Price_PriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anspruch auf Reduktion geändert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Reductions_ReductionChanged {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Reductions_ReductionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Registrierung erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Register_RegistrationProcessed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Register_RegistrationProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz hinzugefügt.
        /// </summary>
        internal static string EventRegistrar_Backend_Spots_SpotAdded {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Spots_SpotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz entfernt.
        /// </summary>
        internal static string EventRegistrar_Backend_Spots_SpotRemoved {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Spots_SpotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        internal static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausblenden:.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorierte.
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte gesendete Nachricht.
        /// </summary>
        internal static string LastMessage {
            get {
                return ResourceManager.GetString("LastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vor {{daysAgo}} Tagen: {{type}}.
        /// </summary>
        internal static string LastMessageTS {
            get {
                return ResourceManager.GetString("LastMessageTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bezahlt.
        /// </summary>
        internal static string MailingAudience_Paid {
            get {
                return ResourceManager.GetString("MailingAudience_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noch nicht bezahlt.
        /// </summary>
        internal static string MailingAudience_Unpaid {
            get {
                return ResourceManager.GetString("MailingAudience_Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warteliste.
        /// </summary>
        internal static string MailingAudience_WaitingList {
            get {
                return ResourceManager.GetString("MailingAudience_WaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platzhalter für Mails.
        /// </summary>
        internal static string MailPlaceholder {
            get {
                return ResourceManager.GetString("MailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Zahlungsaufforderung.
        /// </summary>
        internal static string MailPlaceholder_AcceptedDate {
            get {
                return ResourceManager.GetString("MailPlaceholder_AcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grund Absage.
        /// </summary>
        internal static string MailPlaceholder_CancellationReason {
            get {
                return ResourceManager.GetString("MailPlaceholder_CancellationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offener Betrag.
        /// </summary>
        internal static string MailPlaceholder_DueAmount {
            get {
                return ResourceManager.GetString("MailPlaceholder_DueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string MailPlaceholder_FirstName {
            get {
                return ResourceManager.GetString("MailPlaceholder_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string MailPlaceholder_LastName {
            get {
                return ResourceManager.GetString("MailPlaceholder_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viel bezahlter Betrag.
        /// </summary>
        internal static string MailPlaceholder_OverpaidAmount {
            get {
                return ResourceManager.GetString("MailPlaceholder_OverpaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezahlter Betrag.
        /// </summary>
        internal static string MailPlaceholder_PaidAmount {
            get {
                return ResourceManager.GetString("MailPlaceholder_PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Partner.
        /// </summary>
        internal static string MailPlaceholder_PartnerName {
            get {
                return ResourceManager.GetString("MailPlaceholder_PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string MailPlaceholder_Phone {
            get {
                return ResourceManager.GetString("MailPlaceholder_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string MailPlaceholder_Price {
            get {
                return ResourceManager.GetString("MailPlaceholder_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum erste Zahlungserinnerung.
        /// </summary>
        internal static string MailPlaceholder_Reminder1Date {
            get {
                return ResourceManager.GetString("MailPlaceholder_Reminder1Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der Plätze.
        /// </summary>
        internal static string MailPlaceholder_SpotList {
            get {
                return ResourceManager.GetString("MailPlaceholder_SpotList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung über offenen Betrag.
        /// </summary>
        internal static string MailPlaceholder_UnpaidAmount {
            get {
                return ResourceManager.GetString("MailPlaceholder_UnpaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreff.
        /// </summary>
        internal static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage.
        /// </summary>
        internal static string MailTemplate {
            get {
                return ResourceManager.GetString("MailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu wenig bezahlt.
        /// </summary>
        internal static string MailType_MoneyOwed {
            get {
                return ResourceManager.GetString("MailType_MoneyOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Erste Zahlung erhalten.
        /// </summary>
        internal static string MailType_PartnerRegistrationFirstPaid {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFirstPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Erste Anmeldung angenommen.
        /// </summary>
        internal static string MailType_PartnerRegistrationFirstPartnerAccepted {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFirstPartnerAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Erste Anmeldung auf Warteliste.
        /// </summary>
        internal static string MailType_PartnerRegistrationFirstPartnerOnWaitingList {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFirstPartnerOnWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Reminder 1.
        /// </summary>
        internal static string MailType_PartnerRegistrationFirstReminder {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFirstReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung bezahlt.
        /// </summary>
        internal static string MailType_PartnerRegistrationFullyPaid {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung angenommen.
        /// </summary>
        internal static string MailType_PartnerRegistrationMatchedAndAccepted {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationMatchedAndAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung auf Warteliste.
        /// </summary>
        internal static string MailType_PartnerRegistrationMatchedOnWaitingList {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationMatchedOnWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Reminder 2.
        /// </summary>
        internal static string MailType_PartnerRegistrationSecondReminder {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationSecondReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung erhalten.
        /// </summary>
        internal static string MailType_RegistrationReceived {
            get {
                return ResourceManager.GetString("MailType_RegistrationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung angenommen.
        /// </summary>
        internal static string MailType_SingleRegistrationAccepted {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung: Reminder 1.
        /// </summary>
        internal static string MailType_SingleRegistrationFirstReminder {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationFirstReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung bezahlt.
        /// </summary>
        internal static string MailType_SingleRegistrationFullyPaid {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung auf Warteliste.
        /// </summary>
        internal static string MailType_SingleRegistrationOnWaitingList {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationOnWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung: Reminder 2.
        /// </summary>
        internal static string MailType_SingleRegistrationSecondReminder {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationSecondReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausverkauft.
        /// </summary>
        internal static string MailType_SoldOut {
            get {
                return ResourceManager.GetString("MailType_SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viel bezahlt.
        /// </summary>
        internal static string MailType_TooMuchPaid {
            get {
                return ResourceManager.GetString("MailType_TooMuchPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilnahmebestätigung.
        /// </summary>
        internal static string MailTypeGroup_Confirmation {
            get {
                return ResourceManager.GetString("MailTypeGroup_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsdifferenzen.
        /// </summary>
        internal static string MailTypeGroup_Payments {
            get {
                return ResourceManager.GetString("MailTypeGroup_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhalten.
        /// </summary>
        internal static string MailTypeGroup_Received {
            get {
                return ResourceManager.GetString("MailTypeGroup_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerungen.
        /// </summary>
        internal static string MailTypeGroup_Reminders {
            get {
                return ResourceManager.GetString("MailTypeGroup_Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warteliste.
        /// </summary>
        internal static string MailTypeGroup_WaitingList {
            get {
                return ResourceManager.GetString("MailTypeGroup_WaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlbetrag.
        /// </summary>
        internal static string MissingAmount {
            get {
                return ResourceManager.GetString("MissingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Treffer gefunden.
        /// </summary>
        internal static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung nicht möglich.
        /// </summary>
        internal static string PartnerNotPossible {
            get {
                return ResourceManager.GetString("PartnerNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung möglich.
        /// </summary>
        internal static string PartnerPossible {
            get {
                return ResourceManager.GetString("PartnerPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ paid }} von {{ total }} bezahlt.
        /// </summary>
        internal static string PaymentProgressTS {
            get {
                return ResourceManager.GetString("PaymentProgressTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auszahlungen.
        /// </summary>
        internal static string Payouts {
            get {
                return ResourceManager.GetString("Payouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduktion.
        /// </summary>
        internal static string Reduction {
            get {
                return ResourceManager.GetString("Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist leider ausverkauft.
        /// </summary>
        internal static string RegistrableSoldOut {
            get {
                return ResourceManager.GetString("RegistrableSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungseingang für:.
        /// </summary>
        internal static string RegistrationCandidatesForIncomingPayment {
            get {
                return ResourceManager.GetString("RegistrationCandidatesForIncomingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückzahlung für:.
        /// </summary>
        internal static string RegistrationCandidatesForOutgoingPayment {
            get {
                return ResourceManager.GetString("RegistrationCandidatesForOutgoingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkungen.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Zahlungserinnerung 1.
        /// </summary>
        internal static string ReminderMail1 {
            get {
                return ResourceManager.GetString("ReminderMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Zahlungserinnerung 2.
        /// </summary>
        internal static string ReminderMail2 {
            get {
                return ResourceManager.GetString("ReminderMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        internal static string Role_Follower {
            get {
                return ResourceManager.GetString("Role_Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Role_Leader {
            get {
                return ResourceManager.GetString("Role_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Namen.
        /// </summary>
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Namen, IBAN, Mitteilung.
        /// </summary>
        internal static string SearchByNameIbanMessage {
            get {
                return ResourceManager.GetString("SearchByNameIbanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absender Alias.
        /// </summary>
        internal static string SenderAlias {
            get {
                return ResourceManager.GetString("SenderAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absender Mail.
        /// </summary>
        internal static string SenderMail {
            get {
                return ResourceManager.GetString("SenderMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerungsmail senden.
        /// </summary>
        internal static string SendReminderMail {
            get {
                return ResourceManager.GetString("SendReminderMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerungs-SMS senden.
        /// </summary>
        internal static string SendReminderSms {
            get {
                return ResourceManager.GetString("SendReminderSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgeglichene.
        /// </summary>
        internal static string Settled {
            get {
                return ResourceManager.GetString("Settled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung nicht möglich.
        /// </summary>
        internal static string SingleNotPossible {
            get {
                return ResourceManager.GetString("SingleNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung möglich.
        /// </summary>
        internal static string SinglePossible {
            get {
                return ResourceManager.GetString("SinglePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
    }
}
