//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrar.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventRegistrar.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungsmail.
        /// </summary>
        internal static string AcceptedMail {
            get {
                return ResourceManager.GetString("AcceptedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungseingang zuordnen.
        /// </summary>
        internal static string AssignIncoming {
            get {
                return ResourceManager.GetString("AssignIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsausgang zuordnen.
        /// </summary>
        internal static string AssignOutgoing {
            get {
                return ResourceManager.GetString("AssignOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzahlungen.
        /// </summary>
        internal static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail importiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ExternalMailImported {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ExternalMailImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Mailadresse korrigiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_InvalidAddresses_InvalidEmailAddressFixed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_InvalidAddresses_InvalidEmailAddressFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail freigegeben.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_MailReleased {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_MailReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlung zugeordnet.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Assignments_PaymentAssigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Assignments_PaymentAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungszuordnung zurückgenommen.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Assignments_PaymentUnassigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Assignments_PaymentUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug importiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_Fetch_BankStatementsFileImported {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_Fetch_BankStatementsFileImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoauszug verarbeitet.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_PaymentFileProcessed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_PaymentFileProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild von Einzahlungsschein erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_Files_Slips_PaymentSlipReceived {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_Files_Slips_PaymentSlipReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezahlung am Checkin.
        /// </summary>
        internal static string EventRegistrar_Backend_Payments_PayAtCheckin_WillPayAtCheckinSet {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Payments_PayAtCheckin_WillPayAtCheckinSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_PhoneMessages_SmsReceived {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_PhoneMessages_SmsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS gesendet.
        /// </summary>
        internal static string EventRegistrar_Backend_PhoneMessages_SmsSent {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_PhoneMessages_SmsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partypass reserviert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_FallbackToPartyPassSet {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_FallbackToPartyPassSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung von Warteliste nachgerückt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_PartnerSpotPromotedFromWaitingList {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_PartnerSpotPromotedFromWaitingLis" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Nachrücken aktiviert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_Promotion_AutomaticPromotionActivated {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_Promotion_AutomaticPromotionActiv" +
                        "ated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz von Warteliste nachgerückt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrables_WaitingList_SingleSpotPromotedFromWaitingList {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrables_WaitingList_SingleSpotPromotedFromWaitingList" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung storniert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partneranmeldung teilweise bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPartiallyPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_PartnerRegistrationPartiallyPai" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung bezahlt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Confirmation_SingleRegistrationPaid {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Confirmation_SingleRegistrationPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönlicher Rabatt gewährt.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_IndividualReductions_IndividualReductionAdded {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_IndividualReductions_IndividualReductionAdde" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis wurde neu berechnet.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Price_PriceChanged {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Price_PriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anspruch auf Reduktion geändert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Reductions_ReductionChanged {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Reductions_ReductionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Registrierung erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Register_RegistrationProcessed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Register_RegistrationProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz hinzugefügt.
        /// </summary>
        internal static string EventRegistrar_Backend_Spots_SpotAdded {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Spots_SpotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz entfernt.
        /// </summary>
        internal static string EventRegistrar_Backend_Spots_SpotRemoved {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Spots_SpotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        internal static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausblenden:.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorierte.
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Nachricht: {{type}} vor {{daysAgo}} Tagen.
        /// </summary>
        internal static string LastMessageTS {
            get {
                return ResourceManager.GetString("LastMessageTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlbetrag.
        /// </summary>
        internal static string MissingAmount {
            get {
                return ResourceManager.GetString("MissingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ paid }} von {{ total }} bezahlt.
        /// </summary>
        internal static string PaymentProgressTS {
            get {
                return ResourceManager.GetString("PaymentProgressTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auszahlungen.
        /// </summary>
        internal static string Payouts {
            get {
                return ResourceManager.GetString("Payouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduktion.
        /// </summary>
        internal static string Reduction {
            get {
                return ResourceManager.GetString("Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist leider ausverkauft.
        /// </summary>
        internal static string RegistrableSoldOut {
            get {
                return ResourceManager.GetString("RegistrableSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungseingang für:.
        /// </summary>
        internal static string RegistrationCandidatesForIncomingPayment {
            get {
                return ResourceManager.GetString("RegistrationCandidatesForIncomingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückzahlung für:.
        /// </summary>
        internal static string RegistrationCandidatesForOutgoingPayment {
            get {
                return ResourceManager.GetString("RegistrationCandidatesForOutgoingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkungen.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Zahlungserinnerung 1.
        /// </summary>
        internal static string ReminderMail1 {
            get {
                return ResourceManager.GetString("ReminderMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Zahlungserinnerung 2.
        /// </summary>
        internal static string ReminderMail2 {
            get {
                return ResourceManager.GetString("ReminderMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        internal static string Role_Follower {
            get {
                return ResourceManager.GetString("Role_Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Role_Leader {
            get {
                return ResourceManager.GetString("Role_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Namen.
        /// </summary>
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Namen, IBAN, Mitteilung.
        /// </summary>
        internal static string SearchByNameIbanMessage {
            get {
                return ResourceManager.GetString("SearchByNameIbanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgeglichene.
        /// </summary>
        internal static string Settled {
            get {
                return ResourceManager.GetString("Settled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnort.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
    }
}
