//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrar.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventRegistrar.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail importiert.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ExternalMailImported {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ExternalMailImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_Import_ImportedMailAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail freigegeben.
        /// </summary>
        internal static string EventRegistrar_Backend_Mailing_MailReleased {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Mailing_MailReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_PhoneMessages_SmsReceived {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_PhoneMessages_SmsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung storniert.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Cancel_RegistrationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis wurde neu berechnet.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Price_PriceChanged {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Price_PriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Registrierung erhalten.
        /// </summary>
        internal static string EventRegistrar_Backend_Registrations_Register_RegistrationProcessed {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Registrations_Register_RegistrationProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platz entfernt.
        /// </summary>
        internal static string EventRegistrar_Backend_Spots_SpotRemoved {
            get {
                return ResourceManager.GetString("EventRegistrar_Backend_Spots_SpotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist leider ausverkauft.
        /// </summary>
        internal static string RegistrableSoldOut {
            get {
                return ResourceManager.GetString("RegistrableSoldOut", resourceCulture);
            }
        }
    }
}
