BEGIN TRAN

INSERT INTO [dbo].[Events]
           ([Id]
           ,[PredecessorEventId]
           ,[Name]
           ,[State]
           ,[Acronym]
           ,[Currency]
           ,[AccountIban])
SELECT [Id]
      ,[PredecessorEventId]
	  ,[Name]
      ,[State]
      ,[Acronym]
      ,[Currency]
      ,[AccountIban]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[Events]

INSERT INTO [dbo].[Users]
           ([Id]
           ,[IdentityProvider]
           ,[IdentityProviderUserIdentifier]
           ,[Email]
           ,[FirstName]
           ,[LastName])
SELECT [Id]
      ,[IdentityProvider]
      ,[IdentityProviderUserIdentifier]
      ,[Email]
      ,[FirstName]
      ,[LastName]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[Users]


INSERT INTO [dbo].[UsersInEvents]
           ([Id]
           ,[EventId]
           ,[UserId]
           ,[Role])
SELECT [Id]
      ,[EventId]
      ,[UserId]
      ,[Role]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[UsersInEvents]


INSERT INTO [dbo].[Registrables]
           ([Id]
           ,[EventId]
           ,[HasWaitingList]
           ,[AutomaticPromotionFromWaitingList]
           ,[IsCore]
           ,[MaximumAllowedImbalance]
           ,[MaximumDoubleSeats]
           ,[MaximumSingleSeats]
           ,[Name]
           ,[Price]
           ,[ReducedPrice]
           ,[ShowInMailListOrder]
           ,[CheckinListColumn]
           ,[Type])
SELECT [Id]
      ,[EventId]
      ,[HasWaitingList]
      ,[AutomaticPromotionFromWaitingList]
      ,[IsCore]
      ,[MaximumAllowedImbalance]
      ,[MaximumDoubleSeats]
      ,[MaximumSingleSeats]
      ,[Name]
      ,[Price]
      ,[ReducedPrice]
      ,[ShowInMailListOrder]
      ,[CheckinListColumn]
      ,[Type] = CASE WHEN [MaximumDoubleSeats] IS NULL THEN 1 ELSE 2 END
  FROM [AZURE_ER].[EventRegistrator].[dbo].[Registrables]

INSERT INTO [dbo].[RegistrationForms]
           ([Id]
           ,[EventId]
           ,[ExternalIdentifier]
           ,[State]
           ,[Title])
SELECT [Id]
      ,[EventId]
      ,[ExternalIdentifier]
      ,[State]
      ,[Title]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[RegistrationForms]


INSERT INTO [dbo].[Registrations]
           ([Id]
           ,[EventId]
           ,[RegistrationFormId]
           ,[RegistrationId_Partner]
           ,[AdmittedAt]
           ,[ExternalIdentifier]
           ,[ExternalTimestamp]
           ,[FallbackToPartyPass]
           ,[IsReduced]
           ,[IsWaitingList]
           ,[Language]
           ,[OriginalPrice]
           ,[PartnerNormalized]
           ,[PartnerOriginal]
           ,[Phone]
           ,[PhoneNormalized]
           ,[Price]
           ,[ReceivedAt]
           ,[Remarks]
           ,[RemarksProcessed]
           ,[ReminderLevel]
           ,[RespondentEmail]
           ,[RespondentFirstName]
           ,[RespondentLastName]
           ,[SoldOutMessage]
           ,[State]
           ,[WillPayAtCheckin])
SELECT [Id]
      ,[EventId]
      ,[RegistrationFormId]
	  ,[RegistrationId_Partner]
      ,[AdmittedAt]
      ,[ExternalIdentifier]
      ,[ExternalTimestamp]
      ,[FallbackToPartyPass]
      ,[IsReduced]
      ,[IsWaitingList]
      ,[Language]
      ,[OriginalPrice]
      ,[PartnerNormalized]
      ,[PartnerOriginal]
      ,[Phone]
      ,[PhoneNormalized]
      ,[Price]
      ,[ReceivedAt]
      ,[Remarks]
      ,[RemarksProcessed]
      ,[ReminderLevel]
      ,[RespondentEmail]
      ,[RespondentFirstName]
      ,[RespondentLastName]
      ,[SoldOutMessage]
      ,[State]
      ,[WillPayAtCheckin]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[Registrations]


INSERT INTO [dbo].[Seats]
           ([Id]
           ,[RegistrableId]
           ,[RegistrationId]
           ,[RegistrationId_Follower]
           ,[FirstPartnerJoined]
           ,[IsCancelled]
           ,[IsPartnerSpot]
           ,[IsWaitingList]
           ,[PartnerEmail])
SELECT [Id]
      ,[RegistrableId]
      ,[RegistrationId]
      ,[RegistrationId_Follower]
      ,[FirstPartnerJoined]
      ,[IsCancelled]
      ,[IsPartnerSpot]
      ,[IsWaitingList]
      ,[PartnerEmail]
  FROM [AZURE_ER].[EventRegistrator].[dbo].[Seats]


ROLLBACK
--COMMIT


