//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRegistrar.Backend.Mailing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventRegistrar.Backend.Mailing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bezahlt.
        /// </summary>
        internal static string MailingAudience_Paid {
            get {
                return ResourceManager.GetString("MailingAudience_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noch nicht bezahlt.
        /// </summary>
        internal static string MailingAudience_Unpaid {
            get {
                return ResourceManager.GetString("MailingAudience_Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warteliste.
        /// </summary>
        internal static string MailingAudience_WaitingList {
            get {
                return ResourceManager.GetString("MailingAudience_WaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung: Reminder 1.
        /// </summary>
        internal static string MailType_PartnerRegistrationFirstReminder {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFirstReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung bezahlt.
        /// </summary>
        internal static string MailType_PartnerRegistrationFullyPaid {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung angenommen.
        /// </summary>
        internal static string MailType_PartnerRegistrationMatchedAndAccepted {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationMatchedAndAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paaranmeldung auf Warteliste.
        /// </summary>
        internal static string MailType_PartnerRegistrationMatchedOnWaitingList {
            get {
                return ResourceManager.GetString("MailType_PartnerRegistrationMatchedOnWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung angenommen.
        /// </summary>
        internal static string MailType_SingleRegistrationAccepted {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung: Reminder 1.
        /// </summary>
        internal static string MailType_SingleRegistrationFirstReminder {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationFirstReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung bezahlt.
        /// </summary>
        internal static string MailType_SingleRegistrationFullyPaid {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationFullyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelanmeldung auf Warteliste.
        /// </summary>
        internal static string MailType_SingleRegistrationOnWaitingList {
            get {
                return ResourceManager.GetString("MailType_SingleRegistrationOnWaitingList", resourceCulture);
            }
        }
    }
}
